//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "nanoFrameworkSSD1331_extern.h"
#include "nanoFrameworkSSD1331_extern_nanoFrameworkSSD1331_extern_Utilities.h"

using namespace nanoFrameworkSSD1331_extern;


HRESULT Library_nanoFrameworkSSD1331_extern_nanoFrameworkSSD1331_extern_Utilities::NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_TypedArray_UINT8 param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ARRAY( stack, 0, param0 ) );

        Utilities::NativeGetHardwareSerial( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
    }
    NANOCLR_NOCLEANUP();
}
