//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "nanoFrameworkSSD1331_extern.h"
#include "nanoFrameworkSSD1331_extern_nanoFrameworkSSD1331_extern_Math.h"

using namespace nanoFrameworkSSD1331_extern;


HRESULT Library_nanoFrameworkSSD1331_extern_nanoFrameworkSSD1331_extern_Math::NativeSuperComplicatedCalculation___STATIC__R8__R8( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        double param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_double( stack, 0, param0 ) );

        double retVal = Math::NativeSuperComplicatedCalculation( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_double( stack, retVal );

    }
    NANOCLR_NOCLEANUP();
}
