//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _NANOFRAMEWORKSSD1331_EXTERN_H_
#define _NANOFRAMEWORKSSD1331_EXTERN_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
struct Library_nanoFrameworkSSD1331_extern_nanoFrameworkSSD1331_extern_Math
{
    NANOCLR_NATIVE_DECLARE(NativeSuperComplicatedCalculation___STATIC__R8__R8);

    //--//

};

struct Library_nanoFrameworkSSD1331_extern_nanoFrameworkSSD1331_extern_Utilities
{
    static const int FIELD_STATIC___hardwareSerial = 0;

    NANOCLR_NATIVE_DECLARE(NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFrameworkSSD1331_extern;

#endif  //_NANOFRAMEWORKSSD1331_EXTERN_H_
