//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "nanoFrameworkSSD1331_extern.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_nanoFrameworkSSD1331_extern_nanoFrameworkSSD1331_extern_Math::NativeSuperComplicatedCalculation___STATIC__R8__R8,
    NULL,
    NULL,
    Library_nanoFrameworkSSD1331_extern_nanoFrameworkSSD1331_extern_Utilities::NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFrameworkSSD1331_extern =
{
    "nanoFrameworkSSD1331_extern", 
    0x9CBE1835,
    method_lookup,
    ////////////////////////////////////////////////////////////////////////////////////
    // check if the version bellow matches the one in AssemblyNativeVersion attribute //
    ////////////////////////////////////////////////////////////////////////////////////
    { 1, 0, 0, 0 }
};
